/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-01-13 15:51:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.item;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import item.model.vo.ItemQnaAns;
import java.util.Map;
import item.model.vo.ItemQna;
import item.model.vo.ItemImage;
import java.util.List;
import item.model.vo.Item;
import java.text.DecimalFormat;
import board.model.vo.*;
import member.model.vo.*;

public final class itemView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1578921797434L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1578921797433L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("board.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("item.model.vo.ItemImage");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("item.model.vo.Item");
    _jspx_imports_classes.add("item.model.vo.ItemQnaAns");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("item.model.vo.ItemQna");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   ");
 
   		//로그인한 경우
   		Member memberLoggedIn= (Member)session.getAttribute("memberLoggedIn");

   
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>re:flex</title>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR:100,300,400,500,700,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Libre+Barcode+128+Text|Monoton|Permanent+Marker|Righteous|Seymour+One|Stalinist+One&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\"> <!-- 부트스트랩 -->\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/mypage.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.4.1.js\"></script>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/header.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header class=\"container-fluid navbar-fixed-top\">\r\n");
      out.write("        <div id=\"header-wrapper\" class=\"row\">\r\n");
      out.write("            <div id=\"logo\" class=\"col-md-4\">\r\n");
      out.write("                <h1 class=\"eng\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">re:flex</a></h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"search\" class=\"col-md-4\">\r\n");
      out.write("                <h2 class=\"sr-only\">상품 검색</h2>\r\n");
      out.write("                <form action=\"");
      out.print(request.getContextPath());
      out.write("/item/itemSearch\">\r\n");
      out.write("                    <button type=\"submit\" id=\"btn-search\" aria-label=\"search products\">\r\n");
      out.write("                        <span class=\"glyphicon glyphicon-search\" aria-hidden=\"true\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <input type=\"search\" name=\"search\" placeholder=\"검색\">\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"menu\" class=\"col-md-4\">\r\n");
      out.write("                <ul class=\"list-unstyled list-inline text-right\">\r\n");
      out.write("                    ");
if(memberLoggedIn==null){ 
      out.write("\r\n");
      out.write("                    <li class=\"login-hide\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberLogin\">로그인</a></li>\r\n");
      out.write("                    <li class=\"login-hide\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberEnroll\">회원가입</a></li>\r\n");
      out.write("                    ");
}
                    else{
                    
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t                <li><span class=\"strong\">");
      out.print(memberLoggedIn.getMemberName());
      out.write("</span>님</li>                    \r\n");
      out.write("\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout\">로그아웃</a>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");
if(memberLoggedIn !=null && !"admin".equals(memberLoggedIn.getMemberId())) {
      out.write("\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <h2 class=\"sr-only\">장바구니</h2>\r\n");
      out.write("                        <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberCart?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\" aria-label=\"cart\"><span class=\"glyphicon glyphicon-shopping-cart\" aria-hidden=\"true\"></span></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    ");
} 
      out.write("\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <button type=\"button\"  id=\"btn-sidemenu\">\r\n");
      out.write("                            <span class=\"glyphicon glyphicon-list\" aria-hidden=\"true\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <!-- side menu -->\r\n");
      out.write("                <!-- level1 -->\r\n");
      out.write("                <div id=\"sidemenu-closeLayer\">\r\n");
      out.write("                <nav id=\"level1-sidemenu\" class=\"sidemenu-wrapper\">\r\n");
      out.write("                    <header></header>\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li id=\"recommended\" data-target=\"#level2-recommended\"><a href=\"#\">이럴 때 빌려봐<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\r\n");
      out.write("                        ");
 
                        	//관리자가 로그인한 경우
                        	if(memberLoggedIn != null && "admin".equals(memberLoggedIn.getMemberId())){ 
                        
      out.write("\r\n");
      out.write("                        \t<li id=\"adminPage\" data-target=\"#level2-adminPage\"><a href=\"#\">관리자페이지<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\r\n");
      out.write("\t\t\t\t\t\t");
 
							} 
                        	//로그인한 회원이 있는 경우 마이페이지 메뉴 
                        	else if(memberLoggedIn!=null && !("admin".equals(memberLoggedIn.getMemberId()))){
						
      out.write("\r\n");
      out.write("                        \t<li id=\"mypage\" data-target=\"#level2-mypage\"><a href=\"#\">마이페이지<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\r\n");
      out.write("                        ");

	                        }
                        	//로그인 안했으면 로그인, 회원가입 메뉴 보이게
							else{
                        
      out.write("\r\n");
      out.write("                        \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberLogin\">로그인</a></li>\r\n");
      out.write("                        \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberEnroll\">회원가입</a></li>\r\n");
      out.write("                        ");

							}
                        
      out.write("\r\n");
      out.write("                        <li><a href=\"#\">고객서비스(FAQ)</a></li>\r\n");
      out.write("                        <li><a href=\"#\">re:flex 소개</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <!-- level2: 이럴때빌려봐 -->\r\n");
      out.write("                <nav id=\"level2-recommended\" class=\"sidemenu-wrapper\">\r\n");
      out.write("                    <header class=\"text-center\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\r\n");
      out.write("                        \t<span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("                              이럴 때 빌려봐\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </header>\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT01\">반려동물과 함께 할 때</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT02\">육아할 때</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT03\">파티할 때</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT04\">운동할 때</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT05\">여행갈 때</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT06\">캠핑갈 때</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <!-- level2: 마이페이지 -->\r\n");
      out.write("                ");

                	if(memberLoggedIn != null){
                
      out.write("\r\n");
      out.write("                <nav id=\"level2-mypage\" class=\"sidemenu-wrapper\">\r\n");
      out.write("                    <header class=\"text-center\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\r\n");
      out.write("                            <span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("                            마이페이지\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </header>\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageOrderList?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">주문조회</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageWishlist?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">위시리스트</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageRentalIng?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">계약중인 렌탈</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageRentalFin?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">종료된 렌탈</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypagePoint?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">포인트 확인</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageReview?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">이용후기 내역</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageOneToOne?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">1:1문의 내역</a></li>\r\n");
      out.write("                   \t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberUpdate?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">회원정보 수정</a></li> \r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberDelete?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">회원정보 탈퇴</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                ");

                	}
                
      out.write("\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("                <nav id=\"level2-adminPage\" class=\"sidemenu-wrapper\">\r\n");
      out.write("                    <header class=\"text-center\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\r\n");
      out.write("                            <span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("                            관리자페이지\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </header>\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/member/memberSearch\">회원조회</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/orderList\">배송관리</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/rentalList\">렌탈내역</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/itemSearch\">상품조회</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/member/memberQna\">1:1문의관리</a></li>\r\n");
      out.write("                        \r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/itemEnroll\">상품등록</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/orderOutline\">판매현황</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>");
      out.write('\r');
      out.write('\n');

	String memberId = memberLoggedIn != null?memberLoggedIn.getMemberId():"";
	String categoryNo = (String)request.getAttribute("categoryNo");
	Item item = (Item)request.getAttribute("item");
	List<ItemImage> imgList = (List<ItemImage>)request.getAttribute("imgList");
	
	List<Board> blist = (List<Board>)request.getAttribute("list"); //이용후기 리스트
	List<ItemQna> qList = (List<ItemQna>)request.getAttribute("qList"); //qna 리스트
	Map<Integer, ItemQnaAns> qnaMap = (Map<Integer, ItemQnaAns>)request.getAttribute("qnaMap"); //qna+답변
	
	String reviewPageBar = (String)request.getAttribute("reviewPageBar"); //이용후기 페이지바
	String qnaPageBar = (String)request.getAttribute("qnaPageBar"); //qna 페이지바
	
	int reviewTotalContent = (int)request.getAttribute("reviewTotalContent"); //이용후기 총 게시글 수
	int qnaTotalContent = (int)request.getAttribute("qnaTotalContent"); //qna 총 게시글 수
	
	//가격 콤마찍기
	int discountedPrice7 = (int)Math.ceil((item.getItemPrice()*0.98)/240*7)/100*100; //14일기준
	int discountedPrice14 = (int)Math.ceil((item.getItemPrice()*0.95)/240*14)/100*100; //14일기준
	int discountedPrice30 = (int)Math.ceil((item.getItemPrice()*0.90)/240*30)/100*100; //14일기준
	DecimalFormat dc = new DecimalFormat("###,###,###,###원");
	String price7 = dc.format(discountedPrice7);
	String price14 = dc.format(discountedPrice14);
	String price30 = dc.format(discountedPrice30);
	
	//상품설명
	String desc = item.getItemDesc();
	String[] descArray = desc.split(",");
	

      out.write("\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/itemView.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t//Q&A등록하기 버튼\r\n");
      out.write("\t$('#btn-goQna').on('click', function(){\r\n");
      out.write("\t\tif(");
      out.print(memberLoggedIn==null);
      out.write("){\r\n");
      out.write("\t\t\tgoLogin();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/item/itemQnaForm?categoryNo=");
      out.print(categoryNo);
      out.write("&itemNo=");
      out.print(item.getItemNo());
      out.write("\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//위시리스트 버튼 눌렀을 경우: 회원아이디, 상품번호, 렌탈유형 넘기기\r\n");
      out.write("\t$(\"#btn-wishlist\").on('click', function(){\r\n");
      out.write("\t\tif(");
      out.print(memberLoggedIn==null);
      out.write("){\r\n");
      out.write("\t\t\tgoLogin();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\tif(!confirm(\"현재 상품을 위시리스트에 담으시겠습니까?\")) return;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tlet rentTypeVal = $(\"#rent-type option:selected\").val(); //렌탈유형\r\n");
      out.write("\t\t\tlet rentTypePriceVal = $(\"#rent-type option:selected\").text(); //가격\r\n");
      out.write("\t\t\tconsole.log(rentTypeVal);\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageWishlistInsert\",\r\n");
      out.write("\t\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\t\tdata: {\r\n");
      out.write("\t\t\t\t\tmemberId: \"");
      out.print(memberId);
      out.write("\",\r\n");
      out.write("\t\t\t\t\titemNo: ");
      out.print(item.getItemNo());
      out.write(",\r\n");
      out.write("\t\t\t\t\trentType: rentTypeVal,\r\n");
      out.write("\t\t\t\t\trentTypePrice: rentTypePriceVal\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\t\tsuccess: data => {\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\tlet result = data.result;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(result===1){\r\n");
      out.write("\t\t\t\t\t\tif(!confirm(\"위시리스트에 상품이 담겼습니다.\\n지금 위시리스트를 확인하시겠습니까?\")) return;\r\n");
      out.write("\t\t\t\t\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageWishlist?memberId=");
      out.print(memberId);
      out.write("\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse if(result===-1){\r\n");
      out.write("\t\t\t\t\t\tif(!confirm(\"이미 위시리스트에 존재하는 상품입니다!\\n지금 위시리스트를 확인하시겠습니까?\")) return;\r\n");
      out.write("\t\t\t\t\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageWishlist?memberId=");
      out.print(memberId);
      out.write("\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\talert(\"위시리스트에 상품담기를 실패하였습니다!\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: (jqxhr, textStatus, errorThrown)=>{\r\n");
      out.write("\t\t\t\t\tconsole.log(jqxhr, textStatus, errorThrown);\r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//장바구니 버튼 눌렀을 경우: 회원아이디, 상품번호, 렌탈유형, 수량 넘기기\r\n");
      out.write("\t$(\"#btn-addCart\").on('click', function(){\r\n");
      out.write("\t\tif(");
      out.print(memberLoggedIn==null);
      out.write("){\r\n");
      out.write("\t\t\tgoLogin();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\tlet rentTypeVal = $(\"#rent-type option:selected\").val(); //렌탈유형\r\n");
      out.write("\t\t\tlet orderNoVal = $(\"#orderNo\").val(); //수량\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/member/memberCartInsert\",\r\n");
      out.write("\t\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\t\tdata: {\r\n");
      out.write("\t\t\t\t\tmemberId: \"");
      out.print(memberId);
      out.write("\",\r\n");
      out.write("\t\t\t\t\titemNo: ");
      out.print(item.getItemNo());
      out.write(",\r\n");
      out.write("\t\t\t\t\trentType: rentTypeVal,\r\n");
      out.write("\t\t\t\t\titemQuantity: orderNoVal\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\t\tsuccess: data => {\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(data.result===1){\r\n");
      out.write("\t\t\t\t\t\tif(!confirm(\"장바구니에 상품이 담겼습니다.\\n지금 장바구니를 확인하시겠습니까?\")) return;\r\n");
      out.write("\t\t\t\t\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/member/memberCart?memberId=");
      out.print(memberId);
      out.write("\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse if(data.count===1){\r\n");
      out.write("\t\t\t\t\t\tif(!confirm(\"이미 장바구니에 존재하는 상품입니다!\\n지금 장바구니를 확인하시겠습니까?\")) return;\r\n");
      out.write("\t\t\t\t\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/member/memberCart?memberId=");
      out.print(memberId);
      out.write("\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse if(data.stock===0){\r\n");
      out.write("\t\t\t\t\t\talert(\"이 상품은 현재 품절되었습니다!\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t//장바구니에 이미 담겨있는 현재 상품의 수량과 재고를 비교해서 할 것! \r\n");
      out.write("\t\t\t\t\t/* else if(data.stock>0){\r\n");
      out.write("\t\t\t\t\t\talert(\"선택가능한 상품 수보다 더 많이 선택하셨습니다!\\n현재 선택가능한 상품 수는 [\"+data.stock+\"]입니다.\");\r\n");
      out.write("\t\t\t\t\t\torderNoVal = data.stock;\r\n");
      out.write("\t\t\t\t\t} */\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\talert(\"장바구니에 상품담기를 실패하였습니다!\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: (jqxhr, textStatus, errorThrown)=>{\r\n");
      out.write("\t\t\t\t\tconsole.log(jqxhr, textStatus, errorThrown);\r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//바로렌탈 버튼 눌렀을 경우: 회원아이디, 상품번호, 렌탈유형, 수량 넘기기\r\n");
      out.write("\t$(\"#btn-goRent\").on('click', function(){\r\n");
      out.write("\t\tlet rentTypeVal = $(\"#rent-type option:selected\").val();\r\n");
      out.write("\t\tlet orderNo = document.querySelector(\"#orderNo\").value;\r\n");
      out.write("\r\n");
      out.write("\t\tif(");
      out.print(memberLoggedIn==null);
      out.write("){\r\n");
      out.write("\t\t\tgoLogin();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse {\r\n");
      out.write("\t\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/order/orderOne?memberId=");
      out.print(memberId);
      out.write("&categoryNo=");
      out.print(categoryNo);
      out.write("&itemNo=");
      out.print(item.getItemNo());
      out.write("&rentType=\"+rentTypeVal+\"&ea=\"+orderNo;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}); \r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("function goLogin(){\r\n");
      out.write("\tif(!confirm(\"로그인이 필요한 서비스입니다.\\n로그인 페이지로 이동하시겠습니까?\")) return;\r\n");
      out.write("\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/member/memberLogin\";\r\n");
      out.write("}\r\n");
      out.write("function changeOrderNo(num){\r\n");
      out.write("\tlet stockStr = ");
      out.print(item.getItemStock());
      out.write("; //상품 재고\r\n");
      out.write("\tlet inputOrderNo = document.querySelector(\"#orderNo\");\r\n");
      out.write("\tlet oldNo = inputOrderNo.value;\r\n");
      out.write("\tlet newNo = (inputOrderNo.value*1)+num; //수량(정수형)\r\n");
      out.write("\t\r\n");
      out.write("\tif(newNo < 1) {\r\n");
      out.write("\t\tnewNo = 1;\r\n");
      out.write("\t\talert(\"수량은 반드시 1개 이상 선택되어야 합니다.\");\r\n");
      out.write("\t}\r\n");
      out.write("\tif(newNo > stockStr) {\r\n");
      out.write("\t\tnewNo = stockStr;\r\n");
      out.write("\t\talert(\"수량은 상품재고보다 더 많이 선택될 수 없습니다.\\n현재 상품의 수량은 [\"+stockStr+\"]입니다.\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tinputOrderNo.value = newNo;\r\n");
      out.write("\t\r\n");
      out.write("\t//수량 변경되면 가격 변경\r\n");
      out.write("\tlet totalPrice = document.querySelector(\"#total-price\");\r\n");
      out.write("\tlet curVal = totalPrice.innerText; //현재 선택된 렌탈유형 가격(수량1기준)\r\n");
      out.write("\tlet delIdx = curVal.indexOf('원');\r\n");
      out.write("\tcurVal = curVal.substr(0, delIdx).replace(',','');\r\n");
      out.write("\tcurVal *= 1; //정수형변환\r\n");
      out.write("\tlet plusPrice = curVal; //더하고 뺄 가격 \r\n");
      out.write("\t\r\n");
      out.write("\tlet changeVal = 0; //변경될 가격\r\n");
      out.write("\t\r\n");
      out.write("\t//버튼 누를 때 \r\n");
      out.write("\tconsole.log(\"plus\");\r\n");
      out.write("\tvar selectOption = document.getElementById(\"rent-type\") // 현재 렌탈옵션 element를 모두 가져옴\r\n");
      out.write("\tvar selectOptionInnerHTML = selectOption.options[selectOption.selectedIndex].innerHTML; // 현재 렌탈옵션 element에서 글자를 모두 가져옴\r\n");
      out.write("\tvar replaceSelectOptionInnerHTML = selectOptionInnerHTML.replace(',',''); // replace를 사용해 , 를 없앰\r\n");
      out.write("\tconsole.log(\"zz\"+replaceSelectOptionInnerHTML); // 없앤 , 체크\r\n");
      out.write("\tvar pattern = /(.*)원(.*)/; // 정규식 정의\r\n");
      out.write("\tpattern.test(replaceSelectOptionInnerHTML); // 정규식 실행\r\n");
      out.write("\tvar RegExp_1 = RegExp.$1; // 실행한 정규식의 첫번째 인자를 RegExp_1에 저장. 두번째 인자를 하려면 RegExp.$2로 하기. \r\n");
      out.write("\tconsole.log(\"짠:\"+RegExp_1); // 정규식의 첫번째 인자를 확인\r\n");
      out.write("\t\r\n");
      out.write("\tfor(let i=0; i<newNo; i++){\r\n");
      out.write("\t\tconsole.log(\"1changeVal:\"+changeVal); // 계산된 가격을 log로 찍기\r\n");
      out.write("\t\tchangeVal += (RegExp_1*1); // 수량 만큼 가격을 더하기\r\n");
      out.write("\t\t//console.log(\"changeValAfterPlus=\"+changeVal);\r\n");
      out.write("\t\ttotalPrice.innerText = changeVal.toLocaleString()+\"원\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//console.log(\"changeValAfterPlus=\"+changeVal);\r\n");
      out.write("\ttotalPrice.innerText = changeVal.toLocaleString()+\"원\"; // 마지막에 \"원\" 글자를 붙이기\r\n");
      out.write("\t\r\n");
      out.write("\t//totalPrice.innerText = changeVal.toLocaleString()+\"원\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<!-- page nav -->\r\n");
      out.write("<nav class=\"line-style page-nav\">\r\n");
      out.write("    <ul class=\"list-unstyled list-inline\">\r\n");
      out.write("        <li class=\"go-home\">\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">메인</a>\r\n");
      out.write("            <span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"go-boxmenu\">\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/common/boxMenu?level1=when\">이럴 때 빌려봐</a>\r\n");
      out.write("            <span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("        </li>\r\n");
      out.write("        ");
 
        	if("CT01".equals(categoryNo)){
        
      out.write("\r\n");
      out.write("        \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=");
      out.print(categoryNo);
      out.write("\">반려동물과 함께 할 때</a><span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></li>\r\n");
      out.write("        ");

        	}
        	if("CT02".equals(categoryNo)){
        
      out.write("\r\n");
      out.write("        \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=");
      out.print(categoryNo);
      out.write("\">육아할 때</a><span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></li>\r\n");
      out.write("        ");

        	}
        	if("CT03".equals(categoryNo)){
        
      out.write("\r\n");
      out.write("        \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=");
      out.print(categoryNo);
      out.write("\">파티할 때</a><span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></li>\r\n");
      out.write("        ");

        	}
        	if("CT04".equals(categoryNo)){
        
      out.write("\r\n");
      out.write("        \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=");
      out.print(categoryNo);
      out.write("\">운동할 때</a><span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></li>\r\n");
      out.write("        ");

        	}
        	if("CT05".equals(categoryNo)){
        
      out.write("\r\n");
      out.write("        \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=");
      out.print(categoryNo);
      out.write("\">여행갈 때</a><span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></li>\r\n");
      out.write("        ");

        	}
        	if("CT06".equals(categoryNo)){
        
      out.write("\r\n");
      out.write("        \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=");
      out.print(categoryNo);
      out.write("\">캠핑갈 때</a><span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></li>\r\n");
      out.write("        ");

        	}
        
      out.write("\r\n");
      out.write("        <li>");
      out.print(item.getItemName());
      out.write("</li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div id=\"view-details\" class=\"container-fluid contents none-nav\">\r\n");
      out.write("\t<!-- 상단: 이미지/옵션 영역 -->\r\n");
      out.write("\t<div id=\"view-wrapper\" class=\"row\">\r\n");
      out.write("\t    <section id=\"view-img\" class=\"col-md-6\">\r\n");
      out.write("\t        <h2 class=\"sr-only\">상품 이미지 보기</h2>\r\n");
      out.write("\t        <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/");
      out.print(categoryNo);
      out.write('/');
      out.print(imgList.get(0).getItemImageRenamed() );
      out.write("\" alt=\"상품 대표이미지\">\r\n");
      out.write("\t        ");

	        	//이미지가 2개 이상이라면(서브이미지가 있다면)
				if(imgList.size()>2){
					for(int i=1; i<imgList.size()-1; i++){
	        
      out.write("\r\n");
      out.write("\t        \t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/");
      out.print(categoryNo);
      out.write('/');
      out.print(imgList.get(i).getItemImageRenamed() );
      out.write("\" alt=\"상품 서브이미지\">\r\n");
      out.write("\t        ");

					}
	        	}
	        
      out.write("\r\n");
      out.write("\t    </section>            \r\n");
      out.write("\t    <section id=\"opt-wrapper\" class=\"col-md-6\">\r\n");
      out.write("\t        <div id=\"opt-header\" class=\"row\">\r\n");
      out.write("\t            <div class=\"col-md-6\">\r\n");
      out.write("\t                <p id=\"total-price\" class=\"text-center\">");
      out.print(price14);
      out.write("</p>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <div class=\"col-md-6\">\r\n");
      out.write("\t                <button type=\"button\" id=\"btn-wishlist\" class=\"center-block\">\r\n");
      out.write("\t                   \t 위시리스트에 담기<span class=\"glyphicon glyphicon-heart-empty\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t                </button>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <section id=\"opt-inner\">\r\n");
      out.write("\t            <section>\r\n");
      out.write("\t                <p class=\"pbrand\">");
      out.print(item.getItemBrand());
      out.write("</p>\r\n");
      out.write("\t                <p id=\"pname\">");
      out.print(item.getItemName());
      out.write("</p>\r\n");
      out.write("\t            </section>\r\n");
      out.write("\t            <section id=\"sel-rentType\">\r\n");
      out.write("\t                <p>렌탈옵션</p>\r\n");
      out.write("\t                <label for=\"rent-type\" class='sr-only'>렌탈옵션</label>\r\n");
      out.write("\t                <select name=\"rentType\" id=\"rent-type\">\r\n");
      out.write("\t                    <option value=\"7\"><span class=\"rt-price\">");
      out.print(price7);
      out.write("</span><span class=\"period\">/일시납 7일</option>\r\n");
      out.write("\t                    <option value=\"14\" selected><span class=\"rt-price\">");
      out.print(price14);
      out.write("</span><span class=\"period\">/일시납 14일</option>\r\n");
      out.write("\t                    <option value=\"30\"><span class=\"rt-price\">");
      out.print(price30);
      out.write("</span><span class=\"period\">/일시납 30일</option>\r\n");
      out.write("\t                </select>\r\n");
      out.write("\t            </section>\r\n");
      out.write("\t            <section id=\"sel-amount\">\r\n");
      out.write("\t                <p>수량</p>\r\n");
      out.write("\t                <label for=\"\" class=\"sr-only\">구매수량</label>\r\n");
      out.write("\t                <button type=\"button\" class=\"btn-minus\" onclick=\"changeOrderNo(-1);\"><span class=\"glyphicon glyphicon-minus\" aria-hidden=\"true\"></span></button>\r\n");
      out.write("\t                <input type=\"text\" name=\"orderNo\" id=\"orderNo\" class=\"text-center\" value=\"1\" readonly>\r\n");
      out.write("\t                <button type=\"button\" class=\"btn-plus\" onclick=\"changeOrderNo(1);\"><span class=\"glyphicon glyphicon-plus\" aria-hidden=\"true\"></span></button>\r\n");
      out.write("\t            </section>\r\n");
      out.write("\t            <div id=\"opt-footer\" class=\"row\">\r\n");
      out.write("\t                <div class=\"col-md-6\">\r\n");
      out.write("\t                    <button type=\"button\" id=\"btn-addCart\" class=\"center-block\">장바구니</button>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <div class=\"col-md-6\">\r\n");
      out.write("\t                    <button type=\"button\" id=\"btn-goRent\" class=\"center-block color-reflex\">바로렌탈</button>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <section id=\"opt-desc\">\r\n");
      out.write("\t            \t<p>제품 고시 정보</p>\r\n");
      out.write("\t            \t<ul class=\"list-unstyled\">\r\n");
      out.write("\t            \t");

	            		for(String str: descArray){	
	            	
      out.write("\r\n");
      out.write("\t            \t\t<li>");
      out.print(str);
      out.write("</li>\r\n");
      out.write("\t            \t");

	            		}
	            	
      out.write("\r\n");
      out.write("\t            \t</ul>\r\n");
      out.write("\t            </section>\r\n");
      out.write("\t        </section>\r\n");
      out.write("\t    </section>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 하단: 상품상세/리뷰/qna 영역 -->\r\n");
      out.write("\t<div id=\"details-wrapper\">\r\n");
      out.write("\t    <section class=\"details-tab\">\r\n");
      out.write("\t        <ul class=\"list-unstyled list-inline row\">\r\n");
      out.write("\t            <li class=\"col-md-3 active\"><button type=\"button\" onclick=\"showContent(this, 'details-img')\">상품상세</button></li>\r\n");
      out.write("\t            <li class=\"col-md-3\"><button type=\"button\" onclick=\"showContent(this, 'details-infoShip');\">배송/반품</button></li>\r\n");
      out.write("\t            <li class=\"col-md-3\"><button type=\"button\" onclick=\"showContent(this, 'details-review');\">이용후기(<span class=\"board-cnt\">");
      out.print(reviewTotalContent );
      out.write("</span>)</button></li>\r\n");
      out.write("\t            <li class=\"col-md-3\"><button type=\"button\" onclick=\"showContent(this, 'details-qna');\">상품Q&A(<span class=\"board-cnt\">");
      out.print(qnaTotalContent );
      out.write("</span>)</button></li>\r\n");
      out.write("\t        </ul>\r\n");
      out.write("\t    </section>\r\n");
      out.write("\t    <div class=\"details-contents row\">\r\n");
      out.write("\t        <div class=\"col-md-1\"></div>\r\n");
      out.write("\t        <div class=\"col-md-10 dc-inner\">\r\n");
      out.write("\t            <!-- 상품상세 -->\r\n");
      out.write("\t            <section id=\"details-img\" class=\"active\">\r\n");
      out.write("\t                <h3 class=\"sr-only\">상품상세이미지</h3>\r\n");
      out.write("\t                <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/");
      out.print(categoryNo);
      out.write('/');
      out.print(imgList.get(imgList.size()-1).getItemImageRenamed());
      out.write("\" alt=\"상품정보이미지\">\r\n");
      out.write("\t            </section>\r\n");
      out.write("\t            <!-- 배송반품 -->\r\n");
      out.write("                <section id=\"details-infoShip\" class=\"center-block\">\r\n");
      out.write("                    <div class=\"info-ship\">\r\n");
      out.write("                        <h3 class=\"sr-only\">배송안내</h3>\r\n");
      out.write("                        <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/info_ship.JPG\" alt=\"배송안내 사진\">\r\n");
      out.write("                        <ul class=\"list-unstyled\">\r\n");
      out.write("                            <li>-주문한 상품은 배송준비 단계 이후에는 주문취소가 불가 합니다.(이후부터는 반품/교환 신청만 가능합니다.)</li>\r\n");
      out.write("                            <li>-렌탈 상품의 경우 창고 출고 과정을 동영상 서비스로 제공하고 있습니다.</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <p class=\"strong\">배송지역</p>\r\n");
      out.write("                        <p>-전국 배송 (단, 일부 상품의 경우 도서/산간지역의 배송이 제한되거나 특정 지역만 배송이 가능합니다.)</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"info-back\">\r\n");
      out.write("                        <h3 class=\"sr-only\">회수안내</h3>\r\n");
      out.write("                        <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/info_back.JPG\" alt=\"회수안내 사진\">\r\n");
      out.write("                        <ul class=\"list-unstyled\">\r\n");
      out.write("                            <li>-보증금은 계약 종료 후 반환 됩니다. 상품의 훼손/구성품 분실 시 정비비가 발생될 수 있으며, 보증금에서 차감후 지급됩니다.</li>\r\n");
      out.write("                            <li>-회수된 상품의 검수 과정을 마이페이지에서 동영상으로 확인할 수 있습니다.</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <p class=\"strong\">공통사항</p>\r\n");
      out.write("                        <ul class=\"list-unstyled\">\r\n");
      out.write("                            <li>-렌탈계약 종료일 5일전에 회수 안내 알림톡/SMS가 발송되며, 회수 당일 날 담당 택배기사(롯데택배로 배송된 상품에 한함)가 연락 후상품을 회수합니다.</li>\r\n");
      out.write("                            <li>-구성품 리스트를 참고하여 상품의 구성품을 확인하시고 받으신 상품 박스에 스티로폼, 비닐 등 배송 시 동봉되었던 충전재와 함께 넣어주시기 바랍니다.</li>\r\n");
      out.write("                            <li>-인수형장기 설치 상품은 별도의 회수가 없습니다.</li>\r\n");
      out.write("                            <li>-픽업상품은 상품을 수령한 매장으로 직접 반품(반송)하셔야 합니다. (택배송 불가)</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"info-return\">\r\n");
      out.write("                        <h3 class=\"sr-only\">교환/반품안내</h3>\r\n");
      out.write("                        <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/info_return.JPG\" alt=\"교환반품안내 사진\">\r\n");
      out.write("                        <p class=\"strong\">교환/ 반품 안내</p>\r\n");
      out.write("                        <ul class=\"list-unstyled\">\r\n");
      out.write("                            <li>-교환/반품 신청은 \"마이페이지-계약중인 렌탈-계약 상세 정보\"에서 계약건 별로 신청 가능 합니다.</li>\r\n");
      out.write("                            <li>-교환 접수가 완료되면 대체상품을 배송해드리면서 기존 상품을 회수합니다.</li>\r\n");
      out.write("                            <li>-반품 시 환불처리는 창고 입고/검수 완료 후에 진행됩니다. (제품 훼손, 구성품 분실시 별도 정비비가 발생할 수 있습니다.)</li>\r\n");
      out.write("                            <li>-회수된 상품의 검수 과정을 마이페이지에서 동영상으로 확인할 수 있습니다.</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <p class=\"strong\">공통사항</p>\r\n");
      out.write("                        <ul class=\"list-unstyled\">\r\n");
      out.write("                            <li>-지정 택배회사가 아닌 타 택배회사를 통해 고객님께서 직접 발송하는 경우 택배비는 본인 부담입니다.</li>\r\n");
      out.write("                            <li>-단순변심으로 인한 반품시, 반품(편도) 배송비가 부과됩니다.</li>\r\n");
      out.write("                            <li>-무료배송 상품의 경우에도 반품시에는 배송비가 적용됩니다.</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </section>\r\n");
      out.write("\t            <!-- 이용후기 -->\r\n");
      out.write("\t            <section id=\"details-review\">\r\n");
      out.write("\t           \t\t");

	                  if(blist!=null && !blist.isEmpty()){
	                
      out.write("\r\n");
      out.write("\t                <section id=\"writed-review\" class=\"list-wrapper\">\r\n");
      out.write("\t                    <h3 class=\"sr-only\">이용후기 리스트</h3>\r\n");
      out.write("\t                    <ul class=\"list-unstyled wishlist-inner\">\r\n");
      out.write("\t\t\t\t           ");
 
				               int c=0;
				              
				               for(Board b : blist){ 
				            	   c++;
				            	   if(b.getItem_no()==item.getItemNo()){
			               
      out.write("\r\n");
      out.write("\t                        <li>\r\n");
      out.write("\t                            <section class=\"dtReview-header row\">\r\n");
      out.write("\t                                <div class=\"star col-md-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
 for(int i=0; i<b.getReview_star(); i++){ 
      out.write("\r\n");
      out.write("\t\t                                <span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t    \t\t\t\t\t\t\t");
} 
      out.write("\t                                \r\n");
      out.write("\t\t    \t\t\t\t\t\t</div>\r\n");
      out.write("\t\t    \t\t\t\t\t\t<div class=\"review-content col-md-7\">\r\n");
      out.write("\t                                    <p>");
      out.print(b.getReview_content() );
      out.write("</p>\r\n");
      out.write("\t                                </div>\r\n");
      out.write("\t                                <div class=\"review-info col-md-2\">\r\n");
      out.write("\t                                    <span class=\"review-writer\">");
      out.print(b.getReview_writer() );
      out.write("</span>\r\n");
      out.write("\t                                    <span class=\"review-slash\"> | </span>\r\n");
      out.write("\t                                    <span class=\"review-date\">");
      out.print(b.getReview_date() );
      out.write("</span>\r\n");
      out.write("\t                                </div>\r\n");
      out.write("\t                            </section>\r\n");
      out.write("\t                        </li>\r\n");
      out.write("\t                   \t ");
 } 
      out.write("\r\n");
      out.write("\t                    ");
 } 
      out.write("\r\n");
      out.write("\t                    </ul>\r\n");
      out.write("\t                </section>\r\n");
      out.write("\t                <!-- 페이징바 -->\r\n");
      out.write("\t                <nav class=\"paging-bar text-center\">\r\n");
      out.write("\t                    <ol class=\"list-unstyled list-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(reviewPageBar );
      out.write("\r\n");
      out.write("\t                    </ol>\r\n");
      out.write("\t                </nav>\r\n");
      out.write("\t                ");

			        	} //end of if(글이 존재할 때)
			        	//등록된 글 없을때
			        	else{
			        
      out.write("\r\n");
      out.write("\t\t\t        \t<div id=\"warning-wrapper\" class=\"content-wrapper text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<p><span class=\"glyphicon glyphicon-remove-circle\" aria-hidden=\"true\"></span>등록된 이용후기가 없습니다.</p> \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t        ");
 } 
      out.write("\r\n");
      out.write("\t            </section>\r\n");
      out.write("\t            <!-- 상품QNA -->\r\n");
      out.write("\t            <section id=\"details-qna\">\r\n");
      out.write("\t                <div class=\"btn-wrapper\">\r\n");
      out.write("\t\t                <!--관리자로 로그인시 문의하기 버튼 안 뜨게 설정-->\r\n");
      out.write("\t\t                ");
if(memberLoggedIn!=null && "admin".equals(memberLoggedIn.getMemberId())){ 
      out.write("\r\n");
      out.write("\t\t                ");
} 
		                else{
		                
      out.write("\r\n");
      out.write("\t\t                    <button type=\"button\" id=\"btn-goQna\" class=\"btn-radius pull-right\">문의하기</button>\r\n");
      out.write("\t\t                ");
} 
      out.write("\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <section id=\"point-list\" class=\"list-wrapper\">\r\n");
      out.write("\t                    <h3 class=\"sr-only\">문의내역 리스트</h3>\r\n");
      out.write("\t                    ");

	                       if(qList!=null && !qList.isEmpty()){
	                     
      out.write("\r\n");
      out.write("\t                    <table class=\"text-center list-tbl\">\r\n");
      out.write("\t                        <thead>\r\n");
      out.write("\t                            <tr class=\"row\">\r\n");
      out.write("\t                                <th class=\"col-md-6 text-center\">문의내용</th>\r\n");
      out.write("\t                                <th class=\"col-md-2 text-center\">답변상태</th>\r\n");
      out.write("\t                                <th class=\"col-md-2 text-center\">작성자</th>\r\n");
      out.write("\t                                <th class=\"col-md-2 text-center\">작성일</th>\r\n");
      out.write("\t                            </tr>\r\n");
      out.write("\t                        </thead>\r\n");
      out.write("\t                        <tbody>\r\n");
      out.write("\t                        ");

	                        		for(ItemQna q: qList){
	                        
      out.write("\r\n");
      out.write("\t                            <tr class=\"row qna-header\">\r\n");
      out.write("\t                                <td class=\"col-md-6 qna-title\">\r\n");
      out.write("\t                                    <button type=\"button\" class=\"center-block\">");
      out.print(q.getItemQnaContent() );
      out.write("</button>\r\n");
      out.write("\t                                </td>\r\n");
      out.write("\t                                ");

	                                	if("Y".equals(q.getItemQnaAnsYn())){
	                                
      out.write("\r\n");
      out.write("\t                                \t\t<td class=\"col-md-2\">답변완료</td>\r\n");
      out.write("\t                                ");

	                                	}
	                                	else{
	                                
      out.write("\r\n");
      out.write("\t                                \t\t<td class=\"col-md-2\">답변대기</td>\r\n");
      out.write("\t                                ");

	                                	}
	                                
      out.write("\r\n");
      out.write("\t                                <td class=\"col-md-2\">");
      out.print(q.getMemberId() );
      out.write("</td>\r\n");
      out.write("\t                                <td class=\"col-md-2\">");
      out.print(q.getItemQnaDate() );
      out.write("</td>\r\n");
      out.write("\t                            </tr>\r\n");
      out.write("\t                            <tr class=\"row qna-view\">\r\n");
      out.write("\t                                <td colspan=\"4\" class=\"col-md-12\">\r\n");
      out.write("\t                                    <div class=\"q-wrapper\">\r\n");
      out.write("\t                                        <span class=\"q-title strong\">Q.</span>\r\n");
      out.write("\t                                        <p class=\"center-block\">");
      out.print(q.getItemQnaContent() );
      out.write("</p>\r\n");
      out.write("\t                                    </div>\r\n");
      out.write("\t                                    <div class=\"q-wrapper\">\r\n");
      out.write("\t                                        <span class=\"q-title strong\">A.</span>\r\n");
      out.write("\t                                        ");

			                                	if("Y".equals(q.getItemQnaAnsYn())){
			                                
      out.write("\r\n");
      out.write("\t\t\t                                \t\t<p class=\"center-block\">");
      out.print(qnaMap.get(q.getItemQnaNo()).getItemQnaAnsContent() );
      out.write("</p>\r\n");
      out.write("\t\t\t                                ");

			                                	}
	                                        
	                                        	/*관리자일 경우 답변대기중일때 답변등록창 뜨게 설정*/
			                                	else if(memberLoggedIn!=null && "admin".equals(memberLoggedIn.getMemberId())){
			                                
      out.write("\r\n");
      out.write("\t\t\t                         \r\n");
      out.write("\t\t\t                                \t<form action=\"");
      out.print(request.getContextPath());
      out.write("/admin/item/qnaAnsInsert?categoryNo=");
      out.print(categoryNo);
      out.write("&itemNo=");
      out.print(item.getItemNo());
      out.write("\" \r\n");
      out.write("\t\t\t                                \t\tmethod=\"post\" name=\"itemQnaCommentFrm\">\r\n");
      out.write("\t\t\t                                \t\t<input type=\"hidden\" name=\"itemQnaNo\" value=\"");
      out.print(q.getItemQnaNo());
      out.write("\" />\r\n");
      out.write("\t\t\t                                \t\t<input type=\"text\" name=\"itemQnaAnsContent\" placeholder=\"상품 QnA 답변\" size=\"80px;\"/>\r\n");
      out.write("\t\t\t                                \t\t<button type=\"submit\" id=\"btn-ansQna\" class=\"btn-radius\">등록</button>\r\n");
      out.write("\t\t\t                                \t</form>\t\r\n");
      out.write("\t\t\t\t                                \t\t\r\n");
      out.write("\t\t\t                                \t\t\r\n");
      out.write("\t\t\t                                ");
 	
			                                	}
	                                        	/*관리자가 아닐시 답변대기중 메세지만 뜨게 설정 */
			                                	else{
			                                
      out.write("\r\n");
      out.write("\t\t\t                                \t\t<p class=\"center-block\">답변대기 중입니다.</p>\r\n");
      out.write("\t\t\t                                ");
  
			                                	}
	                                        
      out.write("\t\r\n");
      out.write("\t\t\t                                \t\r\n");
      out.write("\t                                    </div>\r\n");
      out.write("\t                                </td>\r\n");
      out.write("\t                            </tr>\r\n");
      out.write("\t                        ");

		                        	}
	                        
      out.write("\r\n");
      out.write("\t                        </tbody>\r\n");
      out.write("\t                    </table>\r\n");
      out.write("\t                </section> \r\n");
      out.write("\t                <!-- 페이징바 -->\r\n");
      out.write("\t                <nav class=\"paging-bar text-center\">\r\n");
      out.write("\t                    <ol class=\"list-unstyled list-inline\">\r\n");
      out.write("\t                        ");
      out.print(qnaPageBar );
      out.write("\r\n");
      out.write("\t                    </ol>\r\n");
      out.write("\t                </nav>\r\n");
      out.write("\t            </section>\r\n");
      out.write("\t        ");

	        	} //end of if(글이 존재할 때)
	        	//등록된 글이 없을때
	        	else{
	        
      out.write("\r\n");
      out.write("\t        \t<div id=\"warning-wrapper\" class=\"content-wrapper table-warning text-center\">\r\n");
      out.write("\t\t\t\t\t<p><span class=\"glyphicon glyphicon-remove-circle\" aria-hidden=\"true\"></span>등록된 상품Q&A가 없습니다.</p> \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t        ");
 } 
      out.write("\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"col-md-1\"></div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 맨위로 이동 버튼 -->\r\n");
      out.write("<div id=\"go-to-top\" class=\"btn-bottom\">\r\n");
      out.write("    <button type=\"button\" id=\"btn-gotop\" class=\"center-block\" onclick=\"window.scrollTo(0,0);\">맨 위로 이동</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<footer class=\"container-fluid\">\r\n");
      out.write("\t    <div class=\"line-style\"></div>\r\n");
      out.write("\t    <!-- first line -->\r\n");
      out.write("\t    <div id=\"footer-menu\" class=\"row\">\r\n");
      out.write("\t        <div class=\"col-md-3\">\r\n");
      out.write("\t            <header>회사소개</header>\r\n");
      out.write("\t            <ul class=\"list-unstyled\">\r\n");
      out.write("\t                <li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("\t                <li><a href=\"#\">정책안내</a></li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"col-md-3\">\r\n");
      out.write("\t            <header>고객서비스</header>\r\n");
      out.write("\t            <ul class=\"list-unstyled\">\r\n");
      out.write("\t                <li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("\t                <li><a href=\"#\">1:1문의</a></li>\r\n");
      out.write("\t                <li><a href=\"#\">주문현황</a></li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"col-md-3\">\r\n");
      out.write("\t            <header>문의하기</header>\r\n");
      out.write("\t            <p id=\"q-call\" class=\"lead\">1577-1577</p>\r\n");
      out.write("\t            <p id=\"q-email\" class=\"lead\">reflex@naver.com</p>\r\n");
      out.write("\t            <p>평일 10:00~18:00</p>\r\n");
      out.write("\t            <p>주말 및 공휴일 휴무</p>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"col-md-3\">\r\n");
      out.write("\t            <header>SNS</header>\r\n");
      out.write("\t            <ul class=\"list-unstyled\">\r\n");
      out.write("\t                <li><a href=\"#\">Facebook</a></li>\r\n");
      out.write("\t                <li><a href=\"#\">Instagram</a></li>\r\n");
      out.write("\t                <li><a href=\"#\">Twitter</a></li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <!-- second line -->\r\n");
      out.write("\t    <div id=\"about\" class=\"row\">\r\n");
      out.write("\t        <p class=\"eng\">re:flex</p>\r\n");
      out.write("\t        <p>대표:유찬호<span class=\"bar\"></span>사업자등록번호:419-87-00807<span class=\"bar\"></span>통신판매업신고:제 2017-서울마포-2273호</p>\r\n");
      out.write("\t        <p>주소: 서울특별시 마포구 동교동 203-43 4층<span class=\"bar\"></span>대표전화:1566-6813<span class=\"bar\"></span>FAX:070-7848-0818<span class=\"bar\"></span>이메일:reflex@naver.com</p>\r\n");
      out.write("\t        <p>개인정보관리책임자:유찬호</p>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div id=\"copyright\" class=\"line-style\"><span>ⓒ</span>2019 re:flex</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
