/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-01-14 14:20:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import mypage.model.vo.WishlistItem;
import item.model.vo.ItemImage;
import java.text.DecimalFormat;
import java.util.Map;
import java.util.List;
import member.model.vo.*;

public final class mypageWishlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1579010871282L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1578921797433L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("mypage.model.vo.WishlistItem");
    _jspx_imports_classes.add("item.model.vo.ItemImage");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.text.DecimalFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   ");
 
   		//로그인한 경우
   		Member memberLoggedIn= (Member)session.getAttribute("memberLoggedIn");

   
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>re:flex</title>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR:100,300,400,500,700,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Libre+Barcode+128+Text|Monoton|Permanent+Marker|Righteous|Seymour+One|Stalinist+One&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\"> <!-- 부트스트랩 -->\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/mypage.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.4.1.js\"></script>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/header.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header class=\"container-fluid navbar-fixed-top\">\r\n");
      out.write("        <div id=\"header-wrapper\" class=\"row\">\r\n");
      out.write("            <div id=\"logo\" class=\"col-md-4\">\r\n");
      out.write("                <h1 class=\"eng\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">re:flex</a></h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"search\" class=\"col-md-4\">\r\n");
      out.write("                <h2 class=\"sr-only\">상품 검색</h2>\r\n");
      out.write("                <form action=\"");
      out.print(request.getContextPath());
      out.write("/item/itemSearch\">\r\n");
      out.write("                    <button type=\"submit\" id=\"btn-search\" aria-label=\"search products\">\r\n");
      out.write("                        <span class=\"glyphicon glyphicon-search\" aria-hidden=\"true\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <input type=\"search\" name=\"search\" placeholder=\"검색\">\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"menu\" class=\"col-md-4\">\r\n");
      out.write("                <ul class=\"list-unstyled list-inline text-right\">\r\n");
      out.write("                    ");
if(memberLoggedIn==null){ 
      out.write("\r\n");
      out.write("                    <li class=\"login-hide\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberLogin\">로그인</a></li>\r\n");
      out.write("                    <li class=\"login-hide\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberEnroll\">회원가입</a></li>\r\n");
      out.write("                    ");
}
                    else{
                    
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t                <li><span class=\"strong\">");
      out.print(memberLoggedIn.getMemberName());
      out.write("</span>님</li>                    \r\n");
      out.write("\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout\">로그아웃</a>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t\t\t\t\t");
 	} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");
if(memberLoggedIn !=null && !"admin".equals(memberLoggedIn.getMemberId())) {
      out.write("\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <h2 class=\"sr-only\">장바구니</h2>\r\n");
      out.write("                        <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberCart?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\" aria-label=\"cart\"><span class=\"glyphicon glyphicon-shopping-cart\" aria-hidden=\"true\"></span></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    ");
} 
      out.write("\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <button type=\"button\"  id=\"btn-sidemenu\">\r\n");
      out.write("                            <span class=\"glyphicon glyphicon-list\" aria-hidden=\"true\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <!-- side menu -->\r\n");
      out.write("                <!-- level1 -->\r\n");
      out.write("                <div id=\"sidemenu-closeLayer\">\r\n");
      out.write("                <nav id=\"level1-sidemenu\" class=\"sidemenu-wrapper\">\r\n");
      out.write("                    <header></header>\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li id=\"recommended\" data-target=\"#level2-recommended\"><a href=\"#\">이럴 때 빌려봐<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\r\n");
      out.write("                        ");
 
                        	//관리자가 로그인한 경우
                        	if(memberLoggedIn != null && "admin".equals(memberLoggedIn.getMemberId())){ 
                        
      out.write("\r\n");
      out.write("                        \t<li id=\"adminPage\" data-target=\"#level2-adminPage\"><a href=\"#\">관리자페이지<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\r\n");
      out.write("\t\t\t\t\t\t");
 
							} 
                        	//로그인한 회원이 있는 경우 마이페이지 메뉴 
                        	else if(memberLoggedIn!=null && !("admin".equals(memberLoggedIn.getMemberId()))){
						
      out.write("\r\n");
      out.write("                        \t<li id=\"mypage\" data-target=\"#level2-mypage\"><a href=\"#\">마이페이지<span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span></a></li>\r\n");
      out.write("                        ");

	                        }
                        	//로그인 안했으면 로그인, 회원가입 메뉴 보이게
							else{
                        
      out.write("\r\n");
      out.write("                        \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberLogin\">로그인</a></li>\r\n");
      out.write("                        \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberEnroll\">회원가입</a></li>\r\n");
      out.write("                        ");

							}
                        
      out.write("\r\n");
      out.write("                        <li><a href=\"#\">고객서비스(FAQ)</a></li>\r\n");
      out.write("                        <li><a href=\"#\">re:flex 소개</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <!-- level2: 이럴때빌려봐 -->\r\n");
      out.write("                <nav id=\"level2-recommended\" class=\"sidemenu-wrapper\">\r\n");
      out.write("                    <header class=\"text-center\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\r\n");
      out.write("                        \t<span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("                              이럴 때 빌려봐\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </header>\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT01\">반려동물과 함께 할 때</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT02\">육아할 때</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT03\">파티할 때</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT04\">운동할 때</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT05\">여행갈 때</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemList?categoryNo=CT06\">캠핑갈 때</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <!-- level2: 마이페이지 -->\r\n");
      out.write("                ");

                	if(memberLoggedIn != null){
                
      out.write("\r\n");
      out.write("                <nav id=\"level2-mypage\" class=\"sidemenu-wrapper\">\r\n");
      out.write("                    <header class=\"text-center\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\r\n");
      out.write("                            <span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("                            마이페이지\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </header>\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageOrderList?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">주문조회</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageWishlist?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">위시리스트</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageRentalIng?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">계약중인 렌탈</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageRentalFin?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">종료된 렌탈</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypagePoint?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">포인트 확인</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageReview?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">이용후기 내역</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageOneToOne?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">1:1문의 내역</a></li>\r\n");
      out.write("                   \t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberUpdate?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">회원정보 수정</a></li> \r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberDelete?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\">회원정보 탈퇴</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                ");

                	}
                
      out.write("\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("                <nav id=\"level2-adminPage\" class=\"sidemenu-wrapper\">\r\n");
      out.write("                    <header class=\"text-center\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn-goLevel1\">\r\n");
      out.write("                            <span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("                            관리자페이지\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </header>\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/member/memberSearch\">회원조회</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/orderList\">배송관리</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/rentalList\">렌탈내역</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/itemSearch\">상품조회</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/member/memberQna\">1:1문의관리</a></li>\r\n");
      out.write("                        \r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/itemEnroll\">상품등록</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/orderOutline\">판매현황</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>");
      out.write('\r');
      out.write('\n');

	List<WishlistItem> wishItemList = (List<WishlistItem>)request.getAttribute("wishItemList");
	List<Integer> itemNoList = (List<Integer>)request.getAttribute("itemNoList");
	Map<Integer, List<ItemImage>> imgMap = (Map<Integer, List<ItemImage>>)request.getAttribute("imgMap");
	String pageBar = (String)request.getAttribute("pageBar");
	
	//위시리스트 ajax - 회원아이디 담아놓기
	String memberId = "";
	if(memberLoggedIn!=null) memberId = memberLoggedIn.getMemberId();
	else memberId = "null";

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("document.addEventListener('DOMContentLoaded', function(){\r\n");
      out.write("\tdelChk(); //선택상품 삭제\r\n");
      out.write("\tdelAll(); //전체상품 삭제\r\n");
      out.write("\tchkAll(); //체크박스 전체선택\r\n");
      out.write("\taddCartChk(); //선택상품 장바구니 담기\r\n");
      out.write("});\r\n");
      out.write("//장바구니 담기: 여러개\r\n");
      out.write("function addCartChk(){\r\n");
      out.write("\tlet chkBoxArr = document.querySelectorAll(\"#chkWishlist\"); //체크박스 배열\r\n");
      out.write("\tlet btnAddCartChk = document.querySelector(\".btn-chkAddCart\"); //선택상품 장바구니담기 버튼\r\n");
      out.write("\tlet addInfo = \"\"; //장바구니 추가될 상품정보 담길 변수\r\n");
      out.write("\t\r\n");
      out.write("\tchkBoxArr.forEach(function(obj, idx){\r\n");
      out.write("\t\tobj.addEventListener('change', function(){\r\n");
      out.write("\t\t\tlet val = this.value; //선택한 체크박스의 값\r\n");
      out.write("\t\t\tvar idx = addInfo.indexOf(val); //addInfo에 선택한 체크박스의 값이 담겼는지 여부 \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//체크박스 체크됐고 addInfo에도 없다면 추가\r\n");
      out.write("\t\t\tif(this.checked===true && idx===-1)\r\n");
      out.write("\t\t\t\taddInfo += val+\"/\";\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\taddInfo = addInfo.replace(val+\"/\", \"\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}); //end of for chkBox\r\n");
      out.write("\t\r\n");
      out.write("\tbtnAddCartChk.addEventListener('click', function(){\r\n");
      out.write("\t\tif(");
      out.print(memberLoggedIn!=null);
      out.write("){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/member/memberCartInsertChk\",\r\n");
      out.write("\t\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\t\tdata: {\r\n");
      out.write("\t\t\t\t\tmemberId: \"");
      out.print(memberId);
      out.write("\",\r\n");
      out.write("\t\t\t\t\taddInfo: addInfo\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\t\tsuccess: data => {\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\tlet itemListSize = data.itemListSize; //선택한 상품수 \r\n");
      out.write("\t\t\t\t\tlet result = data.result; //장바구니에 담긴 수\r\n");
      out.write("\t\t\t\t\tlet count = data.count; //중복 수\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//모두 담긴 경우\r\n");
      out.write("\t\t\t\t\tif(itemListSize===result){\r\n");
      out.write("\t\t\t\t\t\tif(!confirm(\"장바구니에 선택한 상품이 모두 담겼습니다.\\n지금 장바구니를 확인하시겠습니까?\")) return;\r\n");
      out.write("\t\t\t\t\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/member/memberCart?memberId=");
      out.print(memberId);
      out.write("\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t//중복이 존재한 경우 \r\n");
      out.write("\t\t\t\t\telse if(count>0 && result+count===itemListSize){\r\n");
      out.write("\t\t\t\t\t\tif(!confirm(\"장바구니에 중복된 상품을 제외한 상품이 담겼습니다.\\n지금 장바구니를 확인하시겠습니까?\")) return;\r\n");
      out.write("\t\t\t\t\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/member/memberCart?memberId=");
      out.print(memberId);
      out.write("\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t//중복이 없는데 result가 더 작다면 품절된 상품 존재\r\n");
      out.write("\t\t\t\t\telse if(count!==0 && result<itemListSize){\r\n");
      out.write("\t\t\t\t\t\tif(!confirm(\"장바구니에 품절된 상품을 제외한 상품이 담겼습니다.\\n지금 장바구니를 확인하시겠습니까?\")) return;\r\n");
      out.write("\t\t\t\t\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/member/memberCart?memberId=");
      out.print(memberId);
      out.write("\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t//장바구니에 이미 담겨있는 현재 상품의 수량과 재고를 비교해서 할 것! \r\n");
      out.write("\t\t\t\t\t/* else if(data.stock>0){\r\n");
      out.write("\t\t\t\t\t\talert(\"선택가능한 상품 수보다 더 많이 선택하셨습니다!\\n현재 선택가능한 상품 수는 [\"+data.stock+\"]입니다.\");\r\n");
      out.write("\t\t\t\t\t\torderNoVal = data.stock;\r\n");
      out.write("\t\t\t\t\t} */\r\n");
      out.write("\t\t\t\t\telse if(result===-1){\r\n");
      out.write("\t\t\t\t\t\talert(\"장바구니에 상품담기를 실패하였습니다!\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: (jqxhr, textStatus, errorThrown)=>{\r\n");
      out.write("\t\t\t\t\tconsole.log(jqxhr, textStatus, errorThrown);\r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t}); //end of ajax\r\n");
      out.write("\t\t} //end of if\r\n");
      out.write("\t});//end of click btn\r\n");
      out.write("}\r\n");
      out.write("//장바구니담기: 1개\r\n");
      out.write("function addCartOne(itemNo, optNo){\r\n");
      out.write("\tif(");
      out.print(memberLoggedIn!=null);
      out.write("){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/member/memberCartInsert\",\r\n");
      out.write("\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\tdata: {\r\n");
      out.write("\t\t\t\tmemberId: \"");
      out.print(memberId);
      out.write("\",\r\n");
      out.write("\t\t\t\titemNo: itemNo,\r\n");
      out.write("\t\t\t\trentType: optNo,\r\n");
      out.write("\t\t\t\titemQuantity: 1\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\tsuccess: data => {\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(data.result===1){\r\n");
      out.write("\t\t\t\t\tif(!confirm(\"장바구니에 상품이 담겼습니다.\\n지금 장바구니를 확인하시겠습니까?\")) return;\r\n");
      out.write("\t\t\t\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/member/memberCart?memberId=");
      out.print(memberId);
      out.write("\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse if(data.count===1){\r\n");
      out.write("\t\t\t\t\tif(!confirm(\"이미 장바구니에 존재하는 상품입니다!\\n지금 장바구니를 확인하시겠습니까?\")) return;\r\n");
      out.write("\t\t\t\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/member/memberCart?memberId=");
      out.print(memberId);
      out.write("\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse if(data.stock===0){\r\n");
      out.write("\t\t\t\t\talert(\"이 상품은 현재 품절되었습니다!\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t//장바구니에 이미 담겨있는 현재 상품의 수량과 재고를 비교해서 할 것! \r\n");
      out.write("\t\t\t\t/* else if(data.stock>0){\r\n");
      out.write("\t\t\t\t\talert(\"선택가능한 상품 수보다 더 많이 선택하셨습니다!\\n현재 선택가능한 상품 수는 [\"+data.stock+\"]입니다.\");\r\n");
      out.write("\t\t\t\t\torderNoVal = data.stock;\r\n");
      out.write("\t\t\t\t} */\r\n");
      out.write("\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\talert(\"장바구니에 상품담기를 실패하였습니다!\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: (jqxhr, textStatus, errorThrown)=>{\r\n");
      out.write("\t\t\t\tconsole.log(jqxhr, textStatus, errorThrown);\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function chkAll(){\r\n");
      out.write("\tlet btnChkAll = document.querySelector(\".btn-chkAll\");\r\n");
      out.write("\tlet chkboxArr = document.querySelectorAll(\".item-chk>input\");\r\n");
      out.write("\t\r\n");
      out.write("\t//전체선택 버튼 클릭\r\n");
      out.write("\tbtnChkAll.addEventListener(\"click\", function(){\r\n");
      out.write("\t\tchkboxArr.forEach(function(obj, idx){\r\n");
      out.write("\t\t\tobj.checked = true;\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("//바로렌탈\r\n");
      out.write("function rentNow(cateNo, itemNo, optNo){\r\n");
      out.write("\tif(");
      out.print(memberLoggedIn!=null);
      out.write(")\r\n");
      out.write("\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/order/orderOne?memberId=");
      out.print(memberId);
      out.write("&categoryNo=\"+cateNo+\"&itemNo=\"+itemNo+\"&rentType=\"+optNo+\"&ea=1\";\r\n");
      out.write("}\r\n");
      out.write("function delAll(){\r\n");
      out.write("\tlet delAllFrm = document.querySelector(\"#delAllFrm\");\r\n");
      out.write("\tlet btnDelAll = document.querySelector(\".btn-chkAllDel\");\r\n");
      out.write("\t\r\n");
      out.write("\t//전체삭제 버튼 클릭\r\n");
      out.write("\tbtnDelAll.addEventListener('click', function(){\r\n");
      out.write("\t\tif(!confirm(\"위시리스트를 전부 삭제하시겠습니까?\")) return;\r\n");
      out.write("\t\tdelAllFrm.submit();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("//상품 한 개 삭제: btn-del에 onclick으로\r\n");
      out.write("function delOne(btn){\r\n");
      out.write("\tlet delChkFrm = document.querySelector(\"#delChkFrm\");\r\n");
      out.write("\tlet inputDelInfo = document.querySelector(\"#delInfo\");\r\n");
      out.write("\t\r\n");
      out.write("\tinputDelInfo.value = btn.value;\r\n");
      out.write("\tconsole.log(inputDelInfo.value);\r\n");
      out.write("\tif(!confirm(\"선택한 상품을 삭제하시겠습니까?\")) return;\r\n");
      out.write("\tdelChkFrm.submit();\r\n");
      out.write("\t\t\r\n");
      out.write("}\r\n");
      out.write("function delChk(){\r\n");
      out.write("\tlet chkBoxArr = document.querySelectorAll(\"#chkWishlist\");\r\n");
      out.write("\tlet btnDelChk = document.querySelector(\".btn-chkDel\");\r\n");
      out.write("\tlet delChkFrm = document.querySelector(\"#delChkFrm\");\r\n");
      out.write("\tlet inputDelInfo = document.querySelector(\"#delInfo\");\r\n");
      out.write("\tlet delInfo = \"\"; //삭제될 상품정보 담길 변수\r\n");
      out.write("\t\r\n");
      out.write("\tchkBoxArr.forEach(function(obj, idx){\r\n");
      out.write("\t\tobj.addEventListener('change', function(){\r\n");
      out.write("\t\t\tlet val = this.value; //선택한 체크박스의 값\r\n");
      out.write("\t\t\tlet idx = delInfo.indexOf(val); //delInfo에 선택한 체크박스의 값이 담겼는지 여부 \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//체크박스 체크됐고 delInfo에도 없다면 추가\r\n");
      out.write("\t\t\tif(this.checked===true && idx===-1)\r\n");
      out.write("\t\t\t\tdelInfo += val+\"/\";\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\tdelInfo = delInfo.replace(val+\"/\", \"\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//input[type=hidden] value값으로 delInfo 넣기\r\n");
      out.write("\t\t\tinputDelInfo.value = delInfo;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//선택상품 삭제하기 버튼 클릭\r\n");
      out.write("\tbtnDelChk.addEventListener('click', function(){\r\n");
      out.write("\t\tif(!confirm(\"선택한 상품을 삭제하시겠습니까?\")) return;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdelChkFrm.submit();\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<!-- page nav -->\r\n");
      out.write("<nav class=\"line-style page-nav\">\r\n");
      out.write("    <ul class=\"list-unstyled list-inline\">\r\n");
      out.write("        <li class=\"go-home\">\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">메인</a>\r\n");
      out.write("            <span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"go-boxmenu\">\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/common/boxMenu?level1=mypage\">마이페이지</a>\r\n");
      out.write("            <span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>위시리스트</li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- 위시리스트 -->\r\n");
      out.write("<div class=\"container-fluid contents\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-1\"></div>\r\n");
      out.write("        ");

         //담긴 상품이 존재할 때
         if(wishItemList!=null && !wishItemList.isEmpty()){
        
      out.write("\r\n");
      out.write("        <div class=\"col-md-10 content-wrapper\">\r\n");
      out.write("            <h2 class=\"sr-only\">위시리스트</h2>\r\n");
      out.write("            <!-- 위시리스트 목록 -->\r\n");
      out.write("            <section class=\"wishlist-wrapper\">\r\n");
      out.write("                <h3 class=\"sr-only\">위시리스트 목록 보기</h3>\r\n");
      out.write("                <ul class=\"list-unstyled wishlist-inner\">\r\n");
      out.write("       \t\t\t\t");

       				for(int i=0; i<wishItemList.size(); i++){
       	         		WishlistItem item = wishItemList.get(i);
       	         		List<ItemImage> imgList = imgMap.get(itemNoList.get(i));
       	         		
       	         		int rentPeriod = 0; //렌탈기간
       	         		double disRate = 0; //할인율
       	         		if("RT01".equals(item.getRentOptNo())){
       	         			rentPeriod = 7;
       	         			disRate = 0.98;
       	         		}
       	         		else if("RT02".equals(item.getRentOptNo())){
       	         			rentPeriod = 14;
       	         			disRate = 0.95;
       	         		}
       	         		else{
       	         			rentPeriod = 30;
       	         			disRate = 0.90;
       	         		}
       	         		//렌탈할인 적용된 가격
       	         		int rentPrice = (int)Math.ceil((item.getItemPrice()*disRate)/240*rentPeriod)/100*100;
       	         		DecimalFormat dc = new DecimalFormat("###,###,###,###원");
       	         		String dP = dc.format(rentPrice);
       				
      out.write("\r\n");
      out.write("                    <li class=\"row\">\r\n");
      out.write("                        <div class=\"item-chk col-md-1 text-center\">\r\n");
      out.write("                            <input type=\"checkbox\" name=\"chkWishlist\" id=\"chkWishlist\" value=\"");
      out.print(item.getItemNo());
      out.write(',');
      out.print(item.getRentOptNo());
      out.write("\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item-img col-md-2\">\r\n");
      out.write("                            <a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemView?categoryNo=");
      out.print(item.getCategoryNo());
      out.write("&itemNo=");
      out.print(item.getItemNo());
      out.write("\" class=\"text-center\">\r\n");
      out.write("                            \t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/");
      out.print(item.getCategoryNo());
      out.write('/');
      out.print(imgList.get(0).getItemImageRenamed());
      out.write("\" alt=\"상품 이미지\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"wish-info item-info col-md-9\">\r\n");
      out.write("                            <a href=\"");
      out.print(request.getContextPath());
      out.write("/item/itemView?categoryNo=");
      out.print(item.getCategoryNo());
      out.write("&itemNo=");
      out.print(item.getItemNo());
      out.write("\">\r\n");
      out.write("                                <p class=\"text-left pbrand\">");
      out.print(item.getItemBrand());
      out.write("</p>\r\n");
      out.write("                                <p class=\"text-left pname\">");
      out.print(item.getItemName());
      out.write("</p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <p class=\"text-left price\">");
      out.print(dP );
      out.write(" /<span class=\"rent-period\">");
      out.print(rentPeriod);
      out.write("일</p>\r\n");
      out.write("                            <p class=\"pull-left rent-type\">일시납</p>\r\n");
      out.write("                            <ul class=\"list-unstyled wishBtn-wrapper\">\r\n");
      out.write("                                <li class=\"btn-del\"><button type=\"button\" onclick=\"delOne(this);\" value=\"");
      out.print(item.getItemNo());
      out.write(',');
      out.print(item.getRentOptNo());
      out.write("\"><span class=\"glyphicon glyphicon-remove\" aria-hidden=\"true\"></span></button></li>\r\n");
      out.write("                                <li class=\"btn-radius btn-addCart\"><button type=\"button\" onclick=\"addCartOne('");
      out.print(item.getItemNo());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(item.getRentOptNo());
      out.write("');\">장바구니</button></li>\r\n");
      out.write("                                <li class=\"btn-radius btn-rentNow\"><button type=\"button\" onclick=\"rentNow('");
      out.print(item.getCategoryNo());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(item.getItemNo());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(item.getRentOptNo());
      out.write("');\">바로렌탈</button></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                ");

                		} //end of for
                
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </section>\r\n");
      out.write("            <!-- 위시리스트 선택옵션 -->\r\n");
      out.write("            <section class=\"itemChk-wrapper\">\r\n");
      out.write("                <h3 class=\"sr-only\">위시리스트 선택옵션</h3>\r\n");
      out.write("                <p>선택상품을</p>\r\n");
      out.write("                <button type=\"button\" class=\"btn-radius btn-chkDel\">삭제하기</button>\r\n");
      out.write("                <button type=\"button\" class=\"btn-radius btn-chkAddCart\">장바구니에 담기</button>\r\n");
      out.write("                <div class=\"btnChkAll-wrapper pull-right\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn-radius btn-chkAll\">전체선택</button>\r\n");
      out.write("                    <button type=\"button\" class=\"btn-radius btn-chkAllDel\">전체삭제</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <form action=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageWishlistDelChk\" id=\"delChkFrm\" method=\"post\">\r\n");
      out.write("                \t<input type=\"hidden\" name=\"memberId\" value=\"");
      out.print(memberLoggedIn.getMemberId());
      out.write("\" />\r\n");
      out.write("                \t<input type=\"hidden\" name=\"delInfo\" id=\"delInfo\" value=\"\" />\r\n");
      out.write("                </form>\r\n");
      out.write("                <form action=\"");
      out.print(request.getContextPath());
      out.write("/mypage/mypageWishlistDelAll\" id=\"delAllFrm\" method=\"post\">\r\n");
      out.write("                \t<input type=\"hidden\" name=\"memberId\" value=\"");
      out.print(memberLoggedIn.getMemberId());
      out.write("\" />\r\n");
      out.write("                </form>\r\n");
      out.write("            </section>\r\n");
      out.write("            <!-- 페이징바 -->\r\n");
      out.write("            <nav class=\"paging-bar text-center\">\r\n");
      out.write("                <ol class=\"list-unstyled list-inline\">\r\n");
      out.write("                \t");
      out.print(pageBar);
      out.write("\r\n");
      out.write("                </ol>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");

        	} //end of if(상품 존재할 때)
        	//위시리스트에 등록된 상품이 없을 때
        	else{
        
      out.write("\r\n");
      out.write("        \t<div id=\"warning-wrapper\" class=\"col-md-10 content-wrapper text-center\">\r\n");
      out.write("\t\t\t\t<p><span class=\"glyphicon glyphicon-remove-circle\" aria-hidden=\"true\"></span>등록된 상품이 없습니다.</p> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        <div class=\"col-md-1\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<footer class=\"container-fluid\">\r\n");
      out.write("\t    <div class=\"line-style\"></div>\r\n");
      out.write("\t    <!-- first line -->\r\n");
      out.write("\t    <div id=\"footer-menu\" class=\"row\">\r\n");
      out.write("\t        <div class=\"col-md-3\">\r\n");
      out.write("\t            <header>회사소개</header>\r\n");
      out.write("\t            <ul class=\"list-unstyled\">\r\n");
      out.write("\t                <li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("\t                <li><a href=\"#\">정책안내</a></li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"col-md-3\">\r\n");
      out.write("\t            <header>고객서비스</header>\r\n");
      out.write("\t            <ul class=\"list-unstyled\">\r\n");
      out.write("\t                <li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("\t                <li><a href=\"#\">1:1문의</a></li>\r\n");
      out.write("\t                <li><a href=\"#\">주문현황</a></li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"col-md-3\">\r\n");
      out.write("\t            <header>문의하기</header>\r\n");
      out.write("\t            <p id=\"q-call\" class=\"lead\">1577-1577</p>\r\n");
      out.write("\t            <p id=\"q-email\" class=\"lead\">reflex@naver.com</p>\r\n");
      out.write("\t            <p>평일 10:00~18:00</p>\r\n");
      out.write("\t            <p>주말 및 공휴일 휴무</p>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"col-md-3\">\r\n");
      out.write("\t            <header>SNS</header>\r\n");
      out.write("\t            <ul class=\"list-unstyled\">\r\n");
      out.write("\t                <li><a href=\"#\">Facebook</a></li>\r\n");
      out.write("\t                <li><a href=\"#\">Instagram</a></li>\r\n");
      out.write("\t                <li><a href=\"#\">Twitter</a></li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <!-- second line -->\r\n");
      out.write("\t    <div id=\"about\" class=\"row\">\r\n");
      out.write("\t        <p class=\"eng\">re:flex</p>\r\n");
      out.write("\t        <p>대표:유찬호<span class=\"bar\"></span>사업자등록번호:419-87-00807<span class=\"bar\"></span>통신판매업신고:제 2017-서울마포-2273호</p>\r\n");
      out.write("\t        <p>주소: 서울특별시 마포구 동교동 203-43 4층<span class=\"bar\"></span>대표전화:1566-6813<span class=\"bar\"></span>FAX:070-7848-0818<span class=\"bar\"></span>이메일:reflex@naver.com</p>\r\n");
      out.write("\t        <p>개인정보관리책임자:유찬호</p>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div id=\"copyright\" class=\"line-style\"><span>ⓒ</span>2019 re:flex</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
